import Head from 'next/head';
import { NextPageWithLayout } from '@/pages/_app';
import { ReactElement } from 'react';
import DefaultLayout from '@/components/layouts/default';

const Page: NextPageWithLayout = () => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div>
          <h2>First test page</h2>
        </div>
      </main>
    </>
  );
}

Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <DefaultLayout>{page}</DefaultLayout>
  )
}

export default Page
