import { useState, ChangeEvent, FormEvent } from 'react';
import Head from 'next/head';
import { Button, Input, Text, Spacer, Card } from '@nextui-org/react';

interface IResponse {
  answer: string;
}

export default function Home() {
  const [file, setFile] = useState<File | null>(null);
  const [question, setQuestion] = useState<string>('');
  const [response, setResponse] = useState<IResponse | null>(null);
  const [error, setError] = useState<string>('');

  const handleFileChange = (e: ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files) {
      setFile(files[0]);
    }
  };

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    if (!file || question.trim() === '') {
      setError('Please provide a PDF and a question.');
      return;
    }

    const formData = new FormData();
    formData.append('file', file);
    formData.append('question', question);

    try {
      const result = await fetch('http://127.0.0.1:5000/analyze', {
        method: 'POST',
        body: formData,
      });

      const data: IResponse = await result.json();

      setResponse(data);
      setError('');
    } catch (err: unknown) {
      if (err instanceof Error) {
        setError(err.message);
      } else {
        setError('An unknown error occurred');
      }
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Text h2>Upload your PDF and ask a question</Text>

        {error && (
          <Card color='error'>
            <Text>{error}</Text>
          </Card>
        )}

        <form onSubmit={handleSubmit}>
          <input type='file'
                 onChange={handleFileChange}
                 accept='.pdf'
          />
          <Spacer y={1} />

          <Input
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder='Your question'
          />

          <Spacer y={1} />

          <Button type='submit'>
            Submit
          </Button>
        </form>

        {response && (
          <>
            <Spacer y={1} />
            <Text h3>Answer:</Text>
            <Card color='success'>
              <Text>{response.answer}</Text>
            </Card>
          </>
        )}
      </main>
    </>
  );
}
